### ISSUE TITLE
Single-line comment followed by empty line and multiline comment results in erroneous output

### ISSUE THREAD

**Issue by jakub-a-wysocki** [ErykMroczek/mofmt#28] opened 2023-12-29 15:53 UTC
Consider the below model:

```modelica
model TestComments

  // Single-line comment

  /*
  Multi-line comment 1
  Multi-line comment 2
  */

end TestComments;
```

If formatter is run on such file, the output has incorrect syntax:

```modelica
model TestComments

// Single-line comment/*
  Multi-line comment 1
  Multi-line comment 2
  */
end TestComments;
```

Suprisingly, is blank line between comments is removed, the output has correct syntax, although the result is not desirable, as indentation of lines 3 and 4 is removed:

```modelica
model TestComments

// Single-line comment
/*
  Multi-line comment 1
  Multi-line comment 2
  */
end TestComments;
```

**Comment by ErykMroczek** [comment] 2024-01-09 14:26
OK, here is the situation.

The error resulting in bad comment syntax will be fixed with the next PR. The indentation thing is a complicated issue.

Comments are syntactically transparent. To somehow handle them, *mofmt* takes, I think reasonable, assumption that comments that precede some token belong to the same production as this token. For 99.9% of the cases it should work as intended. In your snippet comments are handled when formatter handles the `end` keyword, and they receive the same indentation as this token  - zero.

Now, I could introduce some ad hoc logic to handle scenario as in your example, but I would prefer not to. The reasons are:

1. Th current approach works well for 99.9% of the time. People almost always put comments above the block of code that these comments refer to.
2. Situation in your example doesn't seem like a realistic use case - empty class specifiers without any items in the *composition* except of some comments  doesn't occur too often in the real code.

Maybe in the future some idea will occur to me that would allow to account for this scenario in an elegant way. For know the indentation will remain is it is.

**Closed** 2024-01-09 14:27 UTC
Labels: bug
