### ISSUE TITLE
First run does not fully format choices and dymola commands

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#27] opened 2023-12-15 10:32 UTC
I found two cases with similar syntax where running mofmt a second time produces new output:
1. Choices annotations
2. Custom dymola commands

Format this code with mofmt v0.3.5:
```
model X
  parameter Integer control = 0 annotation (choices(choice = 0 "Foo", choice = 1 "Bar"));
  annotation (__Dymola_Commands(file = "modelica://MyLib/Resources/plot.mos" "plot"));
end X;
```

First run gives:
```
model X

  parameter Integer control = 0
    annotation (choices(choice = 0
      "Foo", choice = 1
      "Bar"));

  annotation (__Dymola_Commands(file = "modelica://MyLib/Resources/plot.mos"
    "plot"));

end X;

```

Second run:
```
model X

  parameter Integer control = 0
    annotation (
      choices(
        choice = 0
          "Foo",
        choice = 1
          "Bar"));

  annotation (
    __Dymola_Commands(
      file = "modelica://MyLib/Resources/plot.mos"
        "plot"));

end X;
```

Running it a third time does not give a new result.

**Comment by ErykMroczek** [comment] 2023-12-19 09:38
The output from the second run is consistent with the formatting style as such. I assume that the issue is with the fact that formatter has to be triggered twice to obtain it. With that I agree.

**Comment by m-kessler** [comment] 2023-12-19 09:51
Exactly, that's what I tried to say 😃

**Comment by ErykMroczek** [comment] 2023-12-19 11:30
OK, after some thinking it seems that it cannot be fixed without either a significant rewrite of the formatter logic, or without making it a two-pass formatter. I more inclined towards the second option as I would like to keep the program logic simple.

The issue right now is that the current Python implementation is slow, and with such modification it will become even slower. I plan a rewrite for `0.4.0` release, and one of the goals is to improve the performance.

As this is not a critical bug (just need to run the formatter twice), I will re-assign this issue to the `0.4.0` milestone.

**Closed** 2024-02-05 16:49 UTC
Labels: bug
